[package]
name = "yellhole"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.11.1", features = ["mime", "mime_guess"] }
async-compression = { version = "0.3.15", features = ["zstd", "tokio"] }
axum = "0.5.17"
clap = { version = "4.0.18", features = ["derive"] }
log = "0.4.17"
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
time = { version = "0.3.16", features = ["serde", "formatting", "parsing"] }
tokio = { version = "1.21.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = { version = "2.3.1", features = ["serde"] }
webauthn-rs = { version = "0.4.7", features = ["danger-allow-state-serialisation"] }
