[package]
name = "yellhole"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.11.1", features = ["mime", "mime_guess"] }
axum = "0.5.17"
clap = { version = "4.0.18", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.21.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
