[package]
name = "yellhole"
version = "0.1.0"
edition = "2021"
description = "A simple tumblelog."
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.66"
askama = "0.11.1"
atom_syndication = { version = "0.11.0", default-features = false }
axum = { version = "0.5.17", features = ["multipart", "http2"] }
axum-sessions = "0.3.2"
base64 = { version = "0.13.1", features = ["std"] }
chrono = "0.4.23"
clap = { version = "4.0.26", features = ["derive", "env"] }
constant_time_eq = "0.2.4"
futures = "0.3.25"
hex = "0.4.3"
include_dir = "0.7.3"
mime = "0.3.16"
mime_guess = "2.0.4"
p256 = { version = "0.11.1", features = ["pkcs8"] }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
reqwest = { version = "0.11.13", features = ["stream"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_with = { version = "2.1.0", features = ["base64"] }
sha2 = "0.10.6"
spki = { version = "0.6.0", features = ["std", "alloc"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite", "chrono", "uuid", "offline"] }
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
tokio-util = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = [
    "add-extension",
    "sensitive-headers",
    "trace",
    "set-header",
    "fs",
    "request-id",
    "limit",
] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.2.2", features = ["std", "v4"] }

[dev-dependencies]
reqwest = { version = "0.11.13", features = ["json", "cookies"] }
tempdir = "0.3.7"

[workspace]
members = ["xtask"]
