[package]
name = "yellhole"
version = "0.1.0"
edition = "2021"
description = "A simple tumblelog."
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.66"
askama = "0.11.1"
atom_syndication = "0.11.0"
axum = { version = "0.5.17", features = ["multipart", "http2"] }
axum-sessions = "0.3.1"
chrono = "0.4.22"
clap = { version = "4.0.22", features = ["derive", "env"] }
futures = "0.3.25"
hex = "0.4.3"
mime = "0.3.16"
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
serde = { version = "1.0.147", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite", "chrono", "offline"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
webauthn-rs = { version = "0.4.7", features = ["danger-allow-state-serialisation"] }

[workspace]
members = ["xtask"]
