[package]
name = "yellhole"
version = "0.1.0"
edition = "2021"
description = "A simple tumblelog."
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.66"
askama = "0.11.1"
axum = "0.5.17"
chrono = "0.4.22"
clap = { version = "4.0.18", features = ["derive", "env"] }
log = "0.4.17"
mime = "0.3.16"
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
serde = { version = "1.0.147", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite", "chrono", "uuid", "offline"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
webauthn-rs = { version = "0.4.7", features = ["danger-allow-state-serialisation"] }

[workspace]
members = ["xtask"]
